### ISSUE TITLE
大佬这是关于另一个插件的求助，因为那里找不到反馈页面，如果问题解决我会关闭，抱歉打扰了

### ISSUE THREAD

**Issue by raysers** [yiwangsimple/ComfyUI_GroqChat#3]
大佬我在使用你的另一款插件[ComfyUI-Kolors-MZ-mac](https://github.com/yiwangsimple/ComfyUI-Kolors-MZ-mac)，可最基础的文生图流程都有如下报错，我无力解决只好向你求助，因为那个页面上无法进行任何反馈并且没有任何联系方式，请见谅。

我的设备是M1 pro,OS13.6,torch2.3.0,运行报错如下：

got prompt
!!! Exception during processing !!! module 'ComfyUI-Kolors-MZ-mac.mz_kolors_core' has no attribute 'MZ_ChatGLM3Embeds2Conditioning_call'
Traceback (most recent call last):
  File "/Volumes/raysers/AI/ComfyUI/execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/Volumes/raysers/AI/ComfyUI/execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/Volumes/raysers/AI/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/Volumes/raysers/AI/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/Volumes/raysers/AI/ComfyUI/custom_nodes/ComfyUI-Kolors-MZ-mac/__init__.py", line 104, in embeds2conditioning
    return mz_kolors_core.MZ_ChatGLM3Embeds2Conditioning_call(kwargs)
AttributeError: module 'ComfyUI-Kolors-MZ-mac.mz_kolors_core' has no attribute 'MZ_ChatGLM3Embeds2Conditioning_call'

**Comment by yiwangsimple** [comment]
没事，你看我都很久没更新了 现在大家的注意力都在flux上面 真没必要在这个上面花精力了

**Comment by raysers** [comment]
大佬我根据你的回复去搜索了flux的Mac用法，可我的13.6系统因为bf精度不支持因而用不上。一直到我发现了mflux项目，不仅我的13系统可用,而且速度也不算慢。目前我尝试开发了一个MFlux-ComfyUI项目，但仅仅实现了基础文生图功能。大佬是否有兴趣给予指点或者如果能共同开发那再好不过。我的插件地址是：https://github.com/raysers/Mflux-ComfyUI

**Comment by yiwangsimple** [comment]
太棒了  指点谈不上哈哈哈 我最近精力没放在这个上面 ，等我试用一下你的插件 ，我感觉它会火

**Comment by raysers** [comment]
哈哈，这么多天一直不温不火的，管他呢，有的用我就先用，我其实更佩服隔壁的diffusionkit的comfyui版，就是comfyui-MLX.他那个是基础节点，我这个就有点像高度集成的webui了。目前对mac友好的就数diffusionkit和mflux了，两个各有优点。大佬现在没精力那我先研究着，如果哪天感兴趣了再去我那儿瞧瞧

**Comment by raysers** [comment]
大佬我更新了lora，可以去尝试。同时，因为我对github不太熟悉，有些问题需要你的帮助。

第一，我的界面上一直是零反馈，是否因为我设置错误没有打开提问的渠道，因为你的kolors mac上我也找不到反馈的入口。这也可能是我多心，不准不反馈仅仅是因为项目吸引力不足

第二大人方便的话可以给一个联系方式吗？我总是通过这里反复关闭打开问题来向你求教，这总不方便。我发现我的信息十分封闭，因为但直到目前我找到了你一个同在mac上使用comfyui的用户，我一直找不到大本营，大佬有mac舒适的交流群吗？

又一次打扰到大佬，深觉过意不去，可上面的两个问题我确实需要帮助

**Comment by raysers** [comment]
大佬我更新了lora，可以去尝试。同时，因为我对github不太熟悉，有些问题需要你的帮助。

第一，我的界面上一直是零反馈，是否因为我设置错误没有打开提问的渠道，因为你的kolors mac上我也找不到反馈的入口。这也可能是我多心，没准没反馈仅仅是因为项目吸引力不足

第二大佬方便的话可以给一个联系方式吗？我总是通过这里反复关闭打开问题来向你求教，这总不方便。我发现我的信息十分闭塞，因为直到目前为止我只找到了你一个同在mac上使用comfyui的用户，我一直找不到大本营，大佬有mac comfy的交流群吗？

又一次打扰到大佬，深觉过意不去，可上面的两个问题我确实需要帮助

**Comment by raysers** [comment]
大佬我收到了反馈。证明了不是我的设置问题。因此我关闭这个。我现在已经更新到图生图了，如果有兴趣，随时欢迎去看看，谢谢大佬🙏
