### ISSUE TITLE
image to text 报错

### ISSUE THREAD

**Issue by blueraincoatli** [yiwangsimple/ComfyUI_GroqChat#4]
所有image to text node都有报错, ollama._types.ResponseError: Unsupported type: 'bool'， 另外我看图例里在输出端口下方有个小的checkbox，但我这里就是没有啊，是不是这个原因？
![微信截图_20240913235704](https://github.com/user-attachments/assets/7e646a5e-be48-489f-9b0b-a43871dce187)

**Comment by yiwangsimple** [comment]
不是的  那个标签是另一个插件，不影响。我试了下确实存在这个错误 ，等我修复下

**Comment by yiwangsimple** [comment]
修复好了 你更新下就能正常用了 不好意思 现在才处理这个bug  这个是ollama更新带来的
