### ISSUE TITLE
节点现在不能用了么？各种方法安装永远失败，修复也没用用。

### ISSUE THREAD

**Issue by dkqjhoifh** [yiwangsimple/ComfyUI_GroqChat#5]
这是全球唯一能搭建本地实时对话出图调图开源节点啊！

**Comment by yiwangsimple** [comment]
把报错信息贴一下 我这是正常的

**Comment by dkqjhoifh** [comment]
没有报错，就是一直安装失败，不管是cmd安装，管理器安装，git链接安装，全都失败，修复也无效，依赖项安装了没用，删除冲突依赖的其他节点也没用T-T,永远是这个导入失败结果。
![image](https://github.com/user-attachments/assets/469c8ed8-ed15-4fc4-8b0e-e7ce943a430b)

**Comment by yiwangsimple** [comment]
你这样说我也很懵逼  给我看下后台日志 我才能定位问题

**Comment by dkqjhoifh** [comment]
后来装上了，很奇怪，这个节点的安装成功率很低，一直装，莫名其妙成功了一次。

**Comment by dkqjhoifh** [comment]
有没有办法设计一个支持ollama本地聊天的节点，顺带能够导出ai最后一条回复信息？这样就可以通过设置系统人格，通过聊天让ai生成提示词，每次导出的最后一条回复信息就是沟通得到的最终提示词，这样不用反复修改提示词，可以通过自然语言去出图，修图。也就是实时聊天做甲方，让ai当苦力去干活。

**Comment by yiwangsimple** [comment]
LLM party 你可以试试这个插件
